from sqlalchemy import Boolean, Column, Float, Integer, String

from src.database import Base


class Pokemon(Base):
    __tablename__ = "Pokemon"

    id = Column(Integer, primary_key=True, index=True)
    pokedex_number = Column(Integer)
    name = Column(String)
    german_name = Column(String)
    japanese_name = Column(String)
    generation = Column(Integer)
    is_sub_legendary = Column(Boolean)
    is_legendary = Column(Boolean)
    is_mythical = Column(Boolean)
    species = Column(String)
    type_number = Column(Integer)
    type_1 = Column(String)
    type_2 = Column(String)
    height_m = Column(Float)
    weight_kg = Column(Float)
    abilities_number = Column(Integer)
    ability_1 = Column(String)
    ability_2 = Column(String)
    ability_hidden = Column(String)
    total_points = Column(Integer)
    hp = Column(Integer)
    attack = Column(Integer)
    defense = Column(Integer)
    sp_attack = Column(Integer)
    sp_defense = Column(Integer)
    speed = Column(Integer)
    catch_rate = Column(Integer)
    base_friendship = Column(Integer)
    base_experience = Column(Integer)
    growth_rate = Column(String)
    egg_type_number = Column(Integer)
    egg_type_1 = Column(String)
    egg_type_2 = Column(String)
    percentage_male = Column(Float)
    egg_cycles = Column(Float)
    against_normal = Column(Float)
    against_fire = Column(Float)
    against_water = Column(Float)
    against_electric = Column(Float)
    against_grass = Column(Float)
    against_ice = Column(Float)
    against_fight = Column(Float)
    against_poison = Column(Float)
    against_ground = Column(Float)
    against_flying = Column(Float)
    against_psychic = Column(Float)
    against_bug = Column(Float)
    against_rock = Column(Float)
    against_ghost = Column(Float)
    against_dragon = Column(Float)
    against_dark = Column(Float)
    against_steel = Column(Float)
    against_fairy = Column(Float)
